version: "3"

services:
  trust-server:
    image: ghcr.io/proofofcloud/trust-server:sha-1a72e1827d0f15606ac50d4eebc72d3a160388c7
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - YOUR_CERT_PATH_ON_HOST:/cert
    environment:
      - HTTPS_ENABLED=true
      - MULTISIG_MODE=true
      - HTTPS_KEY_PATH=/cert/YOUR_CERT_KEY_NAME
      - HTTPS_CERT_PATH=/cert/YOUR_CERT_NAME
      - PRIVATE_SSS=${PRIVATE_SSS}
      - SHARED_SSS=${SHARED_SSS}
    ports:
      - 443:8080
